### ISSUE TITLE
Solution seems impossible?

### ISSUE THREAD

**Issue by ShootMe** [vuonghy2442/lonelybot#2]
Heya! Cool to see someone else working on solitaire algorithms. Wanted to check out what you had going and tested a seed from greenfelt

lonecli print greenfelt 815
{"tableau piles": [
["JD"],
["10d","8D"],
["8s","5h","3H"],
["3s","Ac","2h","8H"],
["Kc","Ah","10h","4c","6S"],
["9s","7c","Qd","As","7d","KD"],
["3d","Js","9d","Qc","Jh","2s","9H"]
],"stock": ["7H","4D","AD","JC","2D","10S","KH","KS","3C","6H","7S","6C","2C","5C","4S","5S","QH","4H","5D","10C","QS","8C","9C","6D"],
"foundation": [[],[],[],[]]}

lonecli solve greenfelt 815
The first move it outputs doesn't seem possible if I am to understand what they mean.
Deck Deck   , Deck Deck   , Deck Deck   , Deck Pile(2) 2♣

I take this to mean Draw, Draw, Draw, Move 2♣ on to the 3♥.
This would be impossible since 3 draws would put the 3♣ on the top, and even if there is an extra draw you would have the 6♣ not the 2♣.

Am understanding the moves correctly?

**Comment by vuonghy2442** [comment]
Thank you! That's a bug from generating the Greenfelt game. It's supposed to draw from the end of the stock so given the game it's 2♣. And also in my implementation, the first draw is automatically done, so it should be 4 draw in the standard implementation. I will consider fixing the first Draw later.

**Comment by ShootMe** [comment]
I see, so you are starting from the 6D then? That would be incorrect for the actual deal if that's what you are saying. It should start from the 7H, so I would assume you just need to reverse the stock for greenfelt.

**Comment by vuonghy2442** [comment]
I just pushed the new code. Hopefully it will fix the bug. It's basically just reversed the stock

**Comment by vuonghy2442** [comment]
Thank you for testing my code. Any feedback would be highly appreciated. One of my goal is also finding the shortest move sequence for solvable instances, but it seems to take a lot of work to apply for my current idea. But if I ever attempt that your work would be a great resource!

**Comment by ShootMe** [comment]
Sure! Ill take a deeper look at a later time and give feedback if I see anything. I know very little Rust so hopefully I can understand what is going on.
